steps:
# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east1-docker.pkg.dev/steel-spark-422723-e0/cloudrun-docker/scottapow/scottapow:$COMMIT_SHA', '.']
# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east1-docker.pkg.dev/steel-spark-422723-e0/cloudrun-docker/scottapow/scottapow:$COMMIT_SHA']
# Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
    - 'run'
    - 'deploy'
    - 'scottapow'
    - '--image'
    - 'us-east1-docker.pkg.dev/steel-spark-422723-e0/cloudrun-docker/scottapow/scottapow:$COMMIT_SHA'
    - '--region'
    - 'us-east1'
images:
- 'us-east1-docker.pkg.dev/steel-spark-422723-e0/cloudrun-docker/scottapow/scottapow:$COMMIT_SHA'