// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func coffee() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n    .coffee {\n    }\n  </style><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 40 40\" height=\"100%\" width=\"100%\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"4px\" stroke-linecap=\"round\" class=\"coffee\"><path fill=\"#6F4E37\" d=\"\n        M 2,18\n        L 2,26\n        Q 2,38 17,38\n        Q 30,38 30,26\n        L 30,18\n        Z\n    \"></path> <path d=\"M 30,20 C 38,20 38,29 30,29\"></path> <path stroke-width=\"2px\" d=\"M 10,12 S8,10 12,8 S 6,8 12,4\"></path> <path stroke-width=\"2px\" d=\"M 20,12 S18,10 22,8 S 16,8 22,4\"></path></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
